<a href="https://colab.research.google.com/github/MNTech955/100-days-of-machine-learning/blob/main/Encoding__Categorical__Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('sample_data/customer.csv')
df.sample(5)

    age  gender review education purchased
7    60  Female   Poor    School       Yes
36   34  Female   Good        UG       Yes
10   98  Female   Good        UG       Yes
42   30  Female   Good        PG       Yes
19   97    Male   Poor        PG       Yes

In [3]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 0:2],
    df.iloc[:, -1],
    test_size=0.2
)

from sklearn.preprocessing import OrdinalEncoder

X_train

     review education
44  Average        UG
17     Poor        UG
43     Poor        PG
19     Poor        PG
49     Good        UG
27     Poor        PG
2      Good        PG
7      Poor    School
42     Good        PG
5   Average    School
32  Average        UG
30  Average        UG
13  Average    School
41     Good        PG
29  Average        UG
40     Good    School
8   Average        UG
12     Poor    School
28     Poor    School
47     Good        PG
6      Good    School
36     Good        UG
11     Good        UG
38     Good    School
45     Poor        PG
15     Poor        UG
16     Poor        UG
35     Poor    School
34  Average    School
37  Average        PG
21  Average        PG
24  Average        PG
14     Poor        PG
18     Good    School
20  Average    School
25     Good    School
1      Poor        UG
31     Poor    School
10     Good        UG
39     Poor        PG

In [6]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
X_train = oe.transform(X_train)
X_train

array([[1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.]])

In [10]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

X_train_encoded = oe.fit_transform(X_train)

oe.categories_

[array([0., 1., 2.]), array([0., 1., 2.])]

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

le.classes_   # just call this, don't write array manually

y_train = le.transform(y_train)
y_test = le.transform(y_test)

y_train

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0])