<a href="https://colab.research.google.com/github/MNTech955/100-days-of-machine-learning/blob/main/fetching_data_from_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import requests
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,43.8010,8.718,30163
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.6570,8.686,22784
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,24.1493,8.571,13808
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.2869,8.567,17339
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,17.7232,8.559,9906
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.4677,8.534,18186
6,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,32.1946,8.528,35541
7,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,12.7109,8.515,4573
8,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,24.1547,8.504,19112
9,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,30.3311,8.496,26358
10,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,33.3874,8.494,20460
11,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,13.6137,8.490,315
12,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,32.5058,8.485,30032
13,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,24.9481,8.477,12439
14,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,55.9281,8.470,39458
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,20.4058,8.500,9562
16,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,25.2669,8.464,29571
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,21.7701,8.453,14229
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,15.6342,8.451,4188
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0129,8.443,6468

In [6]:
#Empty DataFrame banaya
#hink of df like an empty Excel sheet
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [8]:
#This loop will run from page 1 to page 428
#
for i in range(1,429):
  #This line sends a request to the movie API.
  #So every loop mein new page ka data aayega.
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    #JSON data ko DataFrame mein convert karna
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,43.8010,8.718,30163
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.6570,8.686,22784
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,24.1493,8.571,13808
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.2869,8.567,17339
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,17.7232,8.559,9906
...,...,...,...,...,...,...,...
8555,294793,All the Old Knives,When the CIA discovers one of its agents leake...,2022-04-08,3.9876,6.000,621
8556,12500,American Ninja,"Joe Armstrong, an orphaned drifter with little...",1985-08-30,2.9591,6.000,478
8557,10900,Surveillance,An FBI agent tracks a serial killer with the h...,2008-02-08,2.3959,6.000,355
8558,531503,Point Blank,A nurse is forced to spring a wounded murder s...,2019-07-12,3.9454,6.000,571
8559,454699,Monster Family,The Wishbone family are far from happy. In an ...,2017-08-24,3.0955,5.999,365

In [9]:
#now we have to convert data to csv
df.to_csv('movies.csv')