<a href="https://colab.research.google.com/github/MNTech955/100-days-of-machine-learning/blob/main/working_with_json_sql_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data Sources:

# JSON
# Can be used in Java and Python.
# API → Returns data in JSON format
# Can be consumed by Java or Python.
# SQL → Data is stored in a database
# Can be queried using SQL and processed further

In [3]:
import pandas as pd
pd.read_json('sample_data/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [9]:
import pandas as pd

# Read JSON
url = 'https://api.exchangerate-api.com/v4/latest/INR'
data = pd.read_json(url)

# Flatten 'rates' dictionary into a DataFrame
rates_df = pd.DataFrame(list(data['rates'].items()), columns=['Currency', 'Rate'])

# Optional: add date and base currency
rates_df['Base'] = data['base']
rates_df['Date'] = data['date']

rates_df

    Currency    Rate Base Date
0        INR  1.0000  NaN  NaT
1        AED  0.0391  NaN  NaT
2        AFN  0.6810  NaN  NaT
3        ALL  0.8680  NaN  NaT
4        AMD  3.9800  NaN  NaT
..       ...     ...  ...  ...
161      YER  2.5500  NaN  NaT
162      ZAR  0.1760  NaN  NaT
163      ZMW  0.2030  NaN  NaT
164      ZWG  0.2680  NaN  NaT
165      ZWL  0.2680  NaN  NaT

[166 rows x 4 columns]